name: m3u_baseUrl

on:
  
  schedule:
    - cron: "*/5 * * * *"
  # run when manually triggered
  workflow_dispatch:
  # run when this file is changed
  push:
    branches:
      - main
    paths:
      - ".github/workflows/m3u_baseUrl.yml"  # change to be the path to this file

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${GITHUB_WORKSPACE}/requirements.txt  # if you have a requirements.txt file

    - name: deneme
      run: python finalcsv_creator.py  # change to be the path to your script

    - name: Add and commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "chore: Update file"
