name: Update M3U Playlist

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt  # Eğer varsa, dependencies dosyanız

      - name: Run the update script
        run: python app.py  # Python scriptinizi çalıştırır
      
      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: Update file"
