name: Update M3U Playlist

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt  # Eğer varsa, dependencies dosyanız

      - name: Run the update script
        run: python app.py  # Python scriptinizi çalıştırır
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add t.m3u
          git commit -m "Updated M3U playlist with new baseurl"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
